### ISSUE TITLE
Not running right on Simulator 

### ISSUE THREAD

**Issue by xieyunbin** [YoYoGames/GMEXT-AppleIAP#12]
Hello,

Extension version：2.0.1
GMS2 versions I have tested：2024.4.1, 2024.2.1, 2024.6.2
Xcode version: 15.4
Device: Mac mini

I encountered some issues while using the IAP demo in GMS2 in different version of iOS. Here are the steps I followed:

1，I created a new blank GMS2 project.
2，I imported the entire IAP demo into the project.
3，I replaced the bundle ID and the product ID with those of my game for testing purposes.
4，I exported the project to Xcode and tested it on a simulator.

iOS version:  17.2

When I pressed the purchase button, the prompt for entering the password appeared. After correctly entering the password, I heard the "ding" sound indicating the password was correct. However, a few seconds after the in-app purchase window disappeared, the password prompt reappeared. This cycle repeated no matter how many times I entered the password, and the purchase never completed successfully.

I recorded a video of the issue, which you can view here:
https://github.com/user-attachments/assets/ab3e1757-26c3-4e9a-8977-431b05001a27

iOS version:  17.5

Crash on building and show the EXC_BAD_ACCESS error.
![QQ图片20240718231745](https://github.com/user-attachments/assets/136e21e6-70bf-435f-973b-8c8057bc158c)

iOS version:  16.4

While I press the iap button, the verification window pops up. I enter my account and password. A few seconds later, it pops up again. After entering it for the 3rd time, the log shows that the verification failed. Unlike version 17.2, this time it does not proceed to the in-app purchase verification screen.
![QQ图片20240718232623](https://github.com/user-attachments/assets/c176aa01-3c8c-4082-8ab8-2b130e0eb9de)

I have not made any changes to the demo other than updating the relevant IDs.

Could you please look into this and provide a fix? Thank you.
@jackerley  @sykhro @iampremo @DiasFranciscoA

**Comment by xieyunbin** [comment]
And one more thing.
ios 17.2 can load the detail of the products, such like price, description. 
But ios 16.4 load it failed. 
ios 17.5 is crash, so ...

**Comment by jzavala-YYG** [comment]
I can confirm 17.0.1 works, you just need use sandbox account if not you will be in a infinity loop as you described.

![Screenshot 2024-07-19 at 3 42 23 p m](https://github.com/user-attachments/assets/3c87d797-5793-41e0-b595-f0096a6d3218)

Next it's going to test over 16.0

**Comment by xieyunbin** [comment]
> I can confirm 17.0.1 works, you just need use sandbox account if not you will be in a infinity loop as you described.
> 
> ![Screenshot 2024-07-19 at 3 42 23 p m](https://private-user-images.githubusercontent.com/114691457/350439983-3c87d797-5793-41e0-b595-f0096a6d3218.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NTMyNDEsIm5iZiI6MTcyMTQ1Mjk0MSwicGF0aCI6Ii8xMTQ2OTE0NTcvMzUwNDM5OTgzLTNjODdkNzk3LTU3OTMtNDFlMC1iNTk1LWYwMDk2YTZkMzIxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQwNTIyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOTMxNWYxMWRhY2RmNGE3ZGNkNjA4ZDUwMDg2MmM2Nzg2NjhjMjc3NzNhZWY2OTUwMGUyNzIxNjg4M2RhOTdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LQPkkVTvYzKEbvblEq49SsGvklP-k4KG_g5X18lkndg)
> 
> Next it's going to test over 16.0

Hi, have you try 17.5 and 17.2? Apple review team will focus on the latest iOS version of every device.

**Comment by jzavala-YYG** [comment]
Sorry for the delay, I had to do a lot of updates on my mac to obtain 17.5 simulators, I can confirm the issue, but it's no related to the extension, exactly same happen with empty projects, please open a new bug ticket.

**Comment by xieyunbin** [comment]
> Sorry for the delay, I had to do a lot of updates on my mac to obtain 17.5 simulators, I can confirm the issue, but it's no related to the extension, exactly same happen with empty projects, please open a new bug ticket.

Yes, you are right about the bug on 17.5. It seems to be the bug on the latest version of GMS2, and I saw that bug report already.

But I am not sure the bug on 17.2 and 16.4 will happen after 17.5 bug be fixed. And most important, all the bugs only show on simulators but not on real device. No matter what type of the device or what version of the os.
