### ISSUE TITLE
iap_IsAuthorisedForPayment() always returns true (on subsequent launches).

### ISSUE THREAD

**Issue by ChopperKhan** [YoYoGames/GMEXT-AppleIAP#13]
This may be the expected result.
I’m using iap_IsAuthorisedForPayment() to verify a connection to the Apple Store, and then either enable or disable my in-game store buttons based on this connection. This is the code I’m using:

**global.iap_enabled = false;
if (!iap_IsAuthorisedForPayment()) { exit; }

global.iap_enabled = true;**

On first launch, if there is no connection my in-game store displays “please try later” buttons.
If there is a connection iap_IsAuthorisedForPayment() returns true and my in-game store buttons display "Buy Now" buttons.

However, on subsequent launches even if there is no connection to Apple (tested by disabling internet), iap_IsAuthorisedForPayment() still returns true. My store purchase buttons are enabled, but no purchases can be made.

I realise this may be the expected result? If so how should we go about checking that there is an Apple Store connection in all subsequent launches to correctly enable or disable in-game store buttons.

**Comment by jzavala-YYG** [comment]
This function it's an direct implementation of [SKPaymentQueue.canMakePayments](https://developer.apple.com/documentation/storekit/skpaymentqueue/1506139-canmakepayments?language=objc)  it's how the function work. 

The interesting thing it's that it's deprecated, and seems the whole extension too, probably we will need create a new extension with the new API.
