### ISSUE TITLE
[FEATURE REQUEST] Implement IAP Promotion related delegate methods

### ISSUE THREAD

**Issue by caroparo** [YoYoGames/GMEXT-AppleIAP#2]
Please refer to Apple's [Promoting In-App Purchases documentation](https://developer.apple.com/documentation/storekit/in-app_purchase/original_api_for_in-app_purchase/promoting_in-app_purchases) and implement required SKPaymentTransactionObserver protocol methods, for GM users to be able to promote IAPs in the app store.

**Comment by jzavala-YYG** [comment]
@YYBartT 

Promoting in-app purchases

https://developer.apple.com/documentation/storekit/skpaymenttransactionobserver/promoting_in-app_purchases?language=objc


https://developer.apple.com/documentation/storekit/skproductstorepromotioncontroller/2915873-fetchstorepromotionorderwithcomp?language=objc
iap_Promotion_Order_Fetch()
ASYNC:
id: ios_promotion_order_fetch
products: 
success: BOOL


https://developer.apple.com/documentation/storekit/skproductstorepromotioncontroller/2915874-updatestorepromotionorder?language=objc
iap_Promotion_Order_Update(products)
products: string json of iap identifiers
ASYNC:
id: ios_promotion_order_update
success: BOOL


https://developer.apple.com/documentation/storekit/skproductstorepromotioncontroller/2915867-fetchstorepromotionvisibilityfor?language=objc
iap_Promotion_Visibility_Fetch(product)
product: String iap identifier 
ASYNC:
id: ios_promotion_visibility_fetch
product: string identifier
visibility: CONSTANT ios_promotion_visibility_default,ios_promotion_visibility_show or ios_promotion_visibility_hide
success:BOOL


https://developer.apple.com/documentation/storekit/skproductstorepromotionvisibility/skproductstorepromotionvisibilitydefault?language=objc
iap_Promotion_Visibility_Update(product,visibility)
product: STRING iap identifier 
visibility CONSTANT ios_promotion_visibility_default,ios_promotion_visibility_show or ios_promotion_visibility_hide
ASYNC:
id: ios_promotion_visibility_update
success: BOOL

/////////////////////////////

Event triggered when promotion purshased get requested
https://developer.apple.com/documentation/storekit/skpaymenttransactionobserver/2877502-paymentqueue?language=objc

ASYNC:
id; ios_promotion_purchase
product


////////////////////
TESTING: https://developer.apple.com/documentation/storekit/in-app_purchase/testing_promoted_in-app_purchases?language=objc
