### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by caroparo** [YoYoGames/GMEXT-AppleIAP#3]
It seems that the xcode project and extension code are not using ARC, yet there are many alloc/init calls without release. 
These can be easily analyzed and caught by XCode -> Product -> Analyze.

**Comment by caroparo** [comment]
Possible solutions:
(1) Apply proper Manual Reference Counting (MRC) to extension code; for example, use autoreleased shortcuts like [NSMutableArray array], [NSMutableDictionary dictionary] in general, call autorelease where applicable, and set synthesized properties to nil in dealloc.

(2) Add compiler flag "-fobjc-arc" to extension "Compiler Flags"(i.e. maccompilerflags) configs and migrate to Automatic Reference Counting (ARC); remove redundant retain, release memory management. This should probably be preferred since most if not all 3rd-party CocoaPods SDKs use ARC. Also, most available sample code on the internet uses ARC.

**Comment by DiasFranciscoA** [comment]
the iOS and tvOS both use the "-fobjc-arc" flag and in the latest update the dylib was also compiled using that flag on. If you still see any possible issues with memory leaks please let us know and reopen the ticket.
