### ISSUE TITLE
Popup delay & no callback for "restore purchases" if nothing was purchased

### ISSUE THREAD

**Issue by COWCATGames** [YoYoGames/GMEXT-AppleIAP#6]
Hello,

I would like to confirm that this behavior is expected:

- When calling iap_PurchaseProduct(), it takes about 6-8 seconds for the purchase popup to appear. (the same thing is instant on Android) That's quite long so I had to implement a "please wait" screen to work around this.

- When calling iap_RestorePurchases(), it also takes about 6-8 seconds to get a result, AND I only get an async callback IF there was a purchase on this account. The first time around I thought this function was broken, until I made a purchase and then the callback works fine. So this forces me to implement a timeout, otherwise the user would wait forever. Is that normal?

- The documentation says "calling iap_Init() is not required because it's done by the extension itself", however if I don't do it, calling iap_AddProduct() returns 1 (extension not initialized) The example project ALSO calls it. So who is right, the code or the documentation?

Do note that I experience the same things with the example project untouched, on the LTS release 2 and the latest beta. Tested with both releases (1.2.1 and 1.1.0)

Best,
Fabrice

**Comment by COWCATGames** [comment]
So this is actually a problem for me.
Apple has rejected my app with this reason:

Guideline 2.1 - Performance - App Completeness

We discovered one or more bugs in your app. Specifically, your app was loading infinitely when purchase in-app purchase items, Please review the details below and complete the next steps. 

Review device details:

- Device type: iPad 
- OS version: iOS 17.2

I have asked for more info, but I suspect they just didn't wait long enough. (if not, I have absolutely no idea how to reproduce this, the purchase window always appears for me, even if this takes time)

Help?

**Comment by COWCATGames** [comment]
Alright, so...after explaining to the Apple review that it took 6-8 seconds for the window to appear, they actually validated my app.
Still, this isn't great, I wish it simply was faster to show up.

**Comment by jzavala-YYG** [comment]
Hello @COWCATGames
Can you you link me to your game?

**Comment by COWCATGames** [comment]
Hi, they are Demetrios and BROK the InvestiGator, not sure what you're asking for exactly but the behavior can be reproduced with the example project. I didn't have trouble with updates after explaining this to Apple.

**Comment by Jerome-Labbe-RedArtGames** [comment]
Hello,

I have the same exact issues on a project not yet released.
Using latest GMS version (2024.2.0.132).

It's even worst for me when calling iap_RestorePurchases(), because even if I made a purchase before, this function will never return a callback 1 out 5 attempts.

**Comment by jzavala-YYG** [comment]
@COWCATGames 
@Jerome-Labbe-RedArtGames 

I did a test using on iPhone7+ over our Apple IAP demo and over InvestiGator.

I can't see a significant time lag, calling iap_PurchaseProduct(productId); takes 2-3 seconds (how can make it  replicate the bug of 8 seconds here?) and calling iap_RestorePurchases(); takes around of 8 seconds (I think this is normal)

You can see my tests in the next 2 videos:

https://github.com/YoYoGames/GMEXT-AppleIAP/assets/114691457/fa2c7e07-2959-4a45-b139-56930eb84172

https://github.com/YoYoGames/GMEXT-AppleIAP/assets/114691457/c3368430-527c-4d93-8b66-e2b91065f6c6

**Comment by Jerome-Labbe-RedArtGames** [comment]
Hi @jzavala-YYG,

Thank you for taking time to test it.
Actually I don't really mind about the time it takes as long as it works.

But the fact that you never get a callback when you call iap_RestorePurchases() if you have never bought the IAP before is I believe an important issue. Do you reproduce this issue too ?

Thanks.

**Comment by COWCATGames** [comment]
> @COWCATGames @Jerome-Labbe-RedArtGames
> 
> I did a test using on iPhone7+ over our Apple IAP demo and over InvestiGator.
> 
> I can't see a significant time lag, calling iap_PurchaseProduct(productId); takes 2-3 seconds (how can make it replicate the bug of 8 seconds here?) and calling iap_RestorePurchases(); takes around of 8 seconds (I think this is normal)
> 
> You can see my tests in the next 2 videos:
> 
>  Apple_IAP_DEMO.MP4 
>  InvestiGator_IAP.MP4

Well what you show is not what I experience. I had calculated and it was more around 5 seconds in my case, which is long enough to wonder "is it working, did I press on that button correctly?" Tested on an iPhone SE 2020 with the LTS, and same on simulators. Not sure why it's different for you. But good to know if it works fine for some people.

And yes iap_RestorePurchases() does not send any callback if you've never bought any IAP, I used a timeout to handle this...

**Comment by jzavala-YYG** [comment]
Now **_iap_RestorePurchases()_** can trigger 2 new events **_ios_restore_success_** or **_ios_restore_failed_**
